name: Build and upload PDF

on:
  push:
    branches: 
      - master
    paths-ignore:
      - ".gitignore"
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: "Kevin_Wu_resume.tex"
          latexmk_use_xelatex: true
          extra_fonts: |
            ./fonts/*.ttf
      - uses: actions/upload-artifact@v3
        with:
          name: Kevin_Wu_resume
          path: Kevin_Wu_resume.pdf

